### ISSUE TITLE
Folders have a default display

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-adapter#76]
Should folder not return 404 by default so they don't show up with a display in Content Studio?

Current behavior:
![image](https://user-images.githubusercontent.com/3340349/214820113-3cfc4065-2f6b-4f4f-94ad-b7df66d77179.png)

**Comment by alansemenov** [comment]
@poi33 check if you have configured mapping for this

**Comment by poi33** [comment]
Part of site-enonic (old code)
