### ISSUE TITLE
Adding a new part creates a warning page in CS

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-adapter#86]
![image](https://user-images.githubusercontent.com/3340349/216963465-60599e55-2613-4d42-ac00-b584e27a431f.png)

This only happends the first time you add it. 
Refreshing the page makes the error rendering dissapear. 
The part works as expected (with empty config) inside preview

**Comment by pmi** [comment]
Couldn't reproduce it but the error hints to a possible solution:
`lib/nextjs-proxy/proxy` imports should've been renamed to `lib/nextjs/proxy` after `lib-nextjs-proxy` was renamed to `lib-nextjs`

@poi33 Can you check if your imports are correct please ? Also make sure that you use the latest version of lib-nextjs, which is currently 0.13.0
